name: Periodic health check

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # run on 1st day of the month
    - cron:  '0,30 14,15,16 1 * *'

jobs:
  health_check_job:
    runs-on: ubuntu-20.04
    steps:
    - name: health check url ping
      uses: jtalk/url-health-check-action@v2
      with:
        # The action will fail if any of the URLs reports either 4xx or 5xx status codes
        # Check the following URL
        url: https://young-reef-70745.herokuapp.com/health
        # Follow redirects, or just report success on 3xx status codes
        follow-redirect: false # Optional, defaults to "false"
        # Fail this action after this many failed attempts
        max-attempts: 2 # Optional, defaults to 1
        # Delay between retries
        retry-delay: 5s # Optional, only applicable to max-attempts > 1
        # Retry all errors, including 404. This option might trigger curl upgrade.
        retry-all: false # Optional, defaults to "false"